version: '3.8'

services:
  db:
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=todo
    ports:
      - '127.0.0.1:5432:5432'
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 30s
      retries: 5
  migrate:
    image: gosom/tern
    volumes:
      - ./migrations:/migrations
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=secret
      - PGDATABASE=todo
    command: ["migrate", "--migrations", "/migrations"]
    healthcheck:
      test: "exit 0"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
