// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package orm

import (
	"time"
)

type Todo struct {
	ID        int32
	Content   string
	UserID    int32
	Completed bool
}

type User struct {
	ID        int32
	Fname     string
	Lname     string
	Email     string
	EncPasswd string
	CreatedAt time.Time
}
